### PR TITLE
Added even better quote.

### PR DESCRIPTION
**Pull request by stocksnut**
New code

### CODE REVIEW

**Comment by stocksnut** [comment]
I can post from Jenkins

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
is this thing on

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
I feel it is ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test. Test it now now now

**Comment by stocksnut** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
test with this

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by stocksnut** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
retest this please

**Comment by morganstake** [comment]
ok to test

**Comment by morganstake** [comment]
ok to test

**Pull request merged**
