### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stocksnut**
Fixed some things...please check it out

### CODE REVIEW

**Comment by morganstake** [comment]
Seems innocuaous, but you typing the comments is sketchy

**Comment by morganstake** [comment]
oops

**Review by morganstake — CHANGES_REQUESTED** [review]
class files shouldn't be checked in

**Review by morganstake — CHANGES_REQUESTED** [review]
The Actual quote: "Here's looking at you, kid."
http://www.shmoop.com/quotes/heres-looking-at-you-kid.html

**Comment by stocksnut** [comment]
Okay I removed the class file and I fixed the freakin' quote

**Review by morganstake — APPROVED** [review]

**Comment by morganstake** [comment]
Took you long enough

**Comment by stocksnut** [comment]
darn not sure I like this pull request review crap!

**Comment by morganstake** [comment]
Agreed. Especially with despotic reviewers.

**Pull request merged**
